version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=https://data.javin.io/api
    volumes:
      - .:/app
      - /app/node_modules
